/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ir_player;

import com.github.sarxos.webcam.Webcam;
import java.awt.image.BufferedImage;

import java.awt.Rectangle;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Graphics;
import java.util.List;
import java.awt.EventQueue;
import java.awt.Color;

/**
 *
 * @author hskinner
 */
public class MainFrame extends javax.swing.JFrame {

    public static final int INITIAL_X = 20;
    public static final int INITIAL_Y = 20;
    public static final int INITIAL_WIDTH = 100;
    public static final int INITIAL_HEIGHT = 100;
    
    public MainFrame() {
        initComponents();
        initCamera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        streamButton = new javax.swing.JToggleButton();
        exitButton = new javax.swing.JButton();
        outputBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        frameRateBox = new javax.swing.JTextField();
        imagePanel = new ir_player.CameraFeedPanel();
        fbYPos = new javax.swing.JTextField();
        fbXPos = new javax.swing.JTextField();
        bbPosLeft = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fbWidth = new javax.swing.JTextField();
        fbHeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bbPosRight = new javax.swing.JButton();
        bbPosUp = new javax.swing.JButton();
        bbPosDown = new javax.swing.JButton();
        bbWidthUp = new javax.swing.JButton();
        bbWidthDown = new javax.swing.JButton();
        bbHeightUp = new javax.swing.JButton();
        bbHeightDown = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("Width");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        streamButton.setText("Stream");
        streamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streamButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        outputBox.setEditable(false);
        outputBox.setBackground(java.awt.Color.lightGray);
        outputBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputBox.setText("IR Player");

        jLabel1.setText("Frame Rate");

        frameRateBox.setEditable(false);
        frameRateBox.setText("<NaN>");

        imagePanel.setMaximumSize(new java.awt.Dimension(640, 480));
        imagePanel.setMinimumSize(new java.awt.Dimension(640, 480));
        imagePanel.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        fbYPos.setText(String.valueOf(MainFrame.INITIAL_Y));

        fbXPos.setText(String.valueOf(MainFrame.INITIAL_X));

        bbPosLeft.setText("<");
        bbPosLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbPosLeftActionPerformed(evt);
            }
        });

        jLabel2.setText("X,Y");

        fbWidth.setText(String.valueOf(MainFrame.INITIAL_WIDTH));

        fbHeight.setText(String.valueOf(MainFrame.INITIAL_HEIGHT));

        jLabel3.setText("Width");

        bbPosRight.setText(">");
        bbPosRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbPosRightActionPerformed(evt);
            }
        });

        bbPosUp.setText("^");
        bbPosUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbPosUpActionPerformed(evt);
            }
        });

        bbPosDown.setText("v");
        bbPosDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbPosDownActionPerformed(evt);
            }
        });

        bbWidthUp.setText("^");
        bbWidthUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbWidthUpActionPerformed(evt);
            }
        });

        bbWidthDown.setText("v");
        bbWidthDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbWidthDownActionPerformed(evt);
            }
        });

        bbHeightUp.setText("^");
        bbHeightUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbHeightUpActionPerformed(evt);
            }
        });

        bbHeightDown.setText("v");
        bbHeightDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbHeightDownActionPerformed(evt);
            }
        });

        jLabel5.setText("Height");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameRateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(streamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bbPosLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bbPosDown, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbPosUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbPosRight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fbXPos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(fbYPos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bbWidthDown, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bbWidthUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fbWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bbHeightUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bbHeightDown, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fbHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bbPosLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bbPosUp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bbPosDown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bbPosRight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fbXPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fbYPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bbWidthUp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fbWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bbWidthDown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bbHeightUp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fbHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bbHeightDown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streamButton)
                    .addComponent(exitButton)
                    .addComponent(outputBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(frameRateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void streamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streamButtonActionPerformed
        streaming = !streaming;
    }//GEN-LAST:event_streamButtonActionPerformed

    private void bbPosLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbPosLeftActionPerformed
        imagePanel.decFBoxX();
    }//GEN-LAST:event_bbPosLeftActionPerformed

    private void bbPosUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbPosUpActionPerformed
        imagePanel.decFBoxY();
    }//GEN-LAST:event_bbPosUpActionPerformed

    private void bbPosDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbPosDownActionPerformed
        imagePanel.incFBoxY();
    }//GEN-LAST:event_bbPosDownActionPerformed

    private void bbPosRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbPosRightActionPerformed
        imagePanel.incFBoxX();
    }//GEN-LAST:event_bbPosRightActionPerformed

    private void bbWidthUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbWidthUpActionPerformed
        imagePanel.incFBoxWidth();
    }//GEN-LAST:event_bbWidthUpActionPerformed

    private void bbWidthDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbWidthDownActionPerformed
        imagePanel.decFBoxWidth();
    }//GEN-LAST:event_bbWidthDownActionPerformed

    private void bbHeightDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbHeightDownActionPerformed
        imagePanel.decFBoxHeight();
    }//GEN-LAST:event_bbHeightDownActionPerformed

    private void bbHeightUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbHeightUpActionPerformed
        imagePanel.incFBoxHeight();
    }//GEN-LAST:event_bbHeightUpActionPerformed

    private static final int IMAGE_UPDATE_TIME = 100;
    private static final int ONE_SECOND        = 1000;
    
    private boolean streaming = false;
    private int frameCtr = 0;
    private Webcam webcam;
    
    private void initCamera() {
        List<Webcam> webcams = Webcam.getWebcams();
        
        if (webcams.size() > 0) {
            webcam = webcams.get(0);
            webcam.open();
        }
        else
            outputBox.setText("ERROR: Could not find camera");
    }
    
    private synchronized void updateIfStreaming() {
        if (streaming) {
            BufferedImage img = webcam.getImage();
            imagePanel.updateImage(img);
            imagePanel.repaint();
            
            Rectangle fboxPos = imagePanel.getFocusBox();
            fbXPos.setText(String.valueOf(fboxPos.x));
            fbYPos.setText(String.valueOf(fboxPos.y));
            fbWidth.setText(String.valueOf(fboxPos.width));
            fbHeight.setText(String.valueOf(fboxPos.height));
            
            ++frameCtr;
        }
    }
    
    private synchronized int retrieveClearFrameCtr() {
        int val = frameCtr;
        frameCtr = 0;
        return val;
    }
    
    private synchronized void updateFrameRate() {
        int frameCtr = retrieveClearFrameCtr();
        frameRateBox.setText(""+frameCtr);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        MainFrame mframe = new MainFrame();
        
        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                mframe.setVisible(true);
            }
        });
        
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                mframe.updateIfStreaming();
                EventQueue.invokeLater(this);
            }
        });
        
        new Timer(ONE_SECOND, new ActionListener() {
            public void actionPerformed(ActionEvent ev) {
                mframe.updateFrameRate();
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbHeightDown;
    private javax.swing.JButton bbHeightUp;
    private javax.swing.JButton bbPosDown;
    private javax.swing.JButton bbPosLeft;
    private javax.swing.JButton bbPosRight;
    private javax.swing.JButton bbPosUp;
    private javax.swing.JButton bbWidthDown;
    private javax.swing.JButton bbWidthUp;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fbHeight;
    private javax.swing.JTextField fbWidth;
    private javax.swing.JTextField fbXPos;
    private javax.swing.JTextField fbYPos;
    private javax.swing.JTextField frameRateBox;
    private ir_player.CameraFeedPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField outputBox;
    private javax.swing.JToggleButton streamButton;
    // End of variables declaration//GEN-END:variables
}
